version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: eventsProject
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  eventsProject:
    depends_on:
      - mysql
    build: ./Dockerfile
    restart: on-failure
    ports:
      - "6868:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/eventsProject?createDatabaseIfNotExist=true
    volumes:
      - spring_data:/app/data
    stdin_open: true
    tty: true

volumes:
    mysql_data:
    mysql_config:
    spring_data:
